#!/usr/bin/env bash
# Update Homebrew formula with per-platform SHA256 hashes for a release.
#
# Usage:
#   ./scripts/update-formula.sh <version> [formula-path]
#
# Arguments:
#   version       Version string (e.g., v1.0.0 or 1.0.0)
#   formula-path  Path to nimbus.rb (default: auto-detected)
#
# Modes of operation:
#
# 1. LOCAL MODE (default when dist/checksums.txt exists):
#    Reads SHA256 hashes from dist/checksums.txt generated by build-binary.sh.
#    This is faster and works without a published GitHub release.
#
# 2. REMOTE MODE (when dist/checksums.txt does not exist):
#    Downloads tarballs from the GitHub release and computes SHA256 hashes.
#    Requires that the release has already been published on GitHub.
#
# Environment variables:
#   HOMEBREW_TAP_REPO  When set (e.g., "the-ai-project-co/homebrew-tap"),
#                      the script clones that repo, updates the formula
#                      inside the clone, commits, and pushes.
#   HOMEBREW_TAP_PATH  Local path to homebrew-tap repo (used instead of clone).
#   GITHUB_TOKEN       Token used for authenticated git push when
#                      HOMEBREW_TAP_REPO is set.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION="${1:?Usage: $0 <version> [formula-path] (e.g., v1.0.0)}"
VERSION_NUM="${VERSION#v}"

REPO="the-ai-project-co/nimbus"
CHECKSUMS_FILE="$ROOT_DIR/dist/checksums.txt"
TEMP_DIR="$(mktemp -d)"

cleanup() { rm -rf "$TEMP_DIR"; }
trap cleanup EXIT

# Cross-platform sed -i (macOS requires '' as separate argument, Linux does not)
sedi() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# ---------------------------------------------------------------------------
# 1. Determine formula path
# ---------------------------------------------------------------------------
if [ -n "${2:-}" ]; then
  FORMULA_PATH="$2"
elif [ -n "${HOMEBREW_TAP_PATH:-}" ]; then
  FORMULA_PATH="${HOMEBREW_TAP_PATH}/Formula/nimbus.rb"
elif [ -n "${HOMEBREW_TAP_REPO:-}" ]; then
  echo "Cloning homebrew-tap repo..."
  git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${HOMEBREW_TAP_REPO}.git" \
    "${TEMP_DIR}/homebrew-tap"
  FORMULA_PATH="${TEMP_DIR}/homebrew-tap/Formula/nimbus.rb"
else
  # Try common local paths
  if [ -f "$ROOT_DIR/../homebrew-tap/Formula/nimbus.rb" ]; then
    FORMULA_PATH="$ROOT_DIR/../homebrew-tap/Formula/nimbus.rb"
  elif [ -f "$ROOT_DIR/Formula/nimbus.rb" ]; then
    FORMULA_PATH="$ROOT_DIR/Formula/nimbus.rb"
  else
    echo "Error: Cannot find formula file. Pass path as second argument."
    echo "  e.g., $0 $VERSION /path/to/homebrew-tap/Formula/nimbus.rb"
    exit 1
  fi
fi

if [ ! -f "${FORMULA_PATH}" ]; then
  echo "Error: Formula not found at ${FORMULA_PATH}"
  exit 1
fi

echo "Formula: ${FORMULA_PATH}"
echo "Version: ${VERSION_NUM}"
echo ""

# ---------------------------------------------------------------------------
# 2. Collect SHA256 hashes (local or remote)
# ---------------------------------------------------------------------------
PLATFORMS=("darwin-arm64" "darwin-x64" "linux-x64" "linux-arm64")
declare -A SHA256S

if [ -f "$CHECKSUMS_FILE" ]; then
  echo "Using local checksums from $CHECKSUMS_FILE"
  echo ""
  for platform in "${PLATFORMS[@]}"; do
    tarball="nimbus-${platform}.tar.gz"
    sha=$(grep "$tarball" "$CHECKSUMS_FILE" | awk '{print $1}' || true)
    if [ -z "$sha" ]; then
      echo "Warning: No checksum found for $tarball in checksums.txt"
      echo "  Available entries:"
      cat "$CHECKSUMS_FILE"
      echo ""
      echo "  Will use placeholder for $platform"
      sha="PLACEHOLDER_SHA256_$(echo "$platform" | tr '-' '_' | tr '[:lower:]' '[:upper:]')"
    fi
    SHA256S["${platform}"]="$sha"
    echo "  ${platform}: ${sha}"
  done
else
  echo "No local checksums found, downloading from GitHub releases..."
  echo ""
  for platform in "${PLATFORMS[@]}"; do
    tarball="nimbus-${platform}.tar.gz"
    url="https://github.com/${REPO}/releases/download/v${VERSION_NUM}/${tarball}"

    echo "Downloading ${tarball}..."
    if ! curl -fsSL "${url}" -o "${TEMP_DIR}/${tarball}"; then
      echo "Error: Failed to download ${url}"
      exit 1
    fi

    sha=$(shasum -a 256 "${TEMP_DIR}/${tarball}" | awk '{print $1}')
    SHA256S["${platform}"]="$sha"
    echo "  SHA256: ${sha}"
  done
fi

echo ""

# ---------------------------------------------------------------------------
# 3. Patch version, URLs, and per-platform SHA256 values
# ---------------------------------------------------------------------------
echo "Updating formula at ${FORMULA_PATH}..."

# Update version
sedi "s|version \".*\"|version \"${VERSION_NUM}\"|" "${FORMULA_PATH}"

# Update download URLs for each platform
for platform in "${PLATFORMS[@]}"; do
  sedi \
    "s|releases/download/v[^/]*/nimbus-${platform}\.tar\.gz|releases/download/v${VERSION_NUM}/nimbus-${platform}.tar.gz|" \
    "${FORMULA_PATH}"
done

# Update SHA256 hashes (the sha256 line immediately follows the url line for
# each platform block).
sedi "/nimbus-darwin-arm64\.tar\.gz/{n;s|sha256 \".*\"|sha256 \"${SHA256S[darwin-arm64]}\"|;}" "${FORMULA_PATH}"
sedi "/nimbus-darwin-x64\.tar\.gz/{n;s|sha256 \".*\"|sha256 \"${SHA256S[darwin-x64]}\"|;}" "${FORMULA_PATH}"
sedi "/nimbus-linux-x64\.tar\.gz/{n;s|sha256 \".*\"|sha256 \"${SHA256S[linux-x64]}\"|;}" "${FORMULA_PATH}"
sedi "/nimbus-linux-arm64\.tar\.gz/{n;s|sha256 \".*\"|sha256 \"${SHA256S[linux-arm64]}\"|;}" "${FORMULA_PATH}"

# ---------------------------------------------------------------------------
# 4. Validate formula syntax
# ---------------------------------------------------------------------------
echo ""
echo "Validating formula syntax..."
if command -v ruby &>/dev/null; then
  if ruby -c "${FORMULA_PATH}"; then
    echo "  Ruby syntax: valid"
  else
    echo "  Warning: Ruby syntax check failed"
    exit 1
  fi
else
  echo "  ruby not available, skipping syntax check"
fi

# ---------------------------------------------------------------------------
# 5. Push to homebrew-tap if we cloned it
# ---------------------------------------------------------------------------
if [ -n "${HOMEBREW_TAP_REPO:-}" ] && [ -d "${TEMP_DIR}/homebrew-tap" ]; then
  cd "${TEMP_DIR}/homebrew-tap"
  git config user.name "github-actions[bot]"
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git add Formula/nimbus.rb
  git diff --cached --quiet || git commit -m "Update nimbus to v${VERSION_NUM}"
  git push
  echo "Pushed formula update to ${HOMEBREW_TAP_REPO}"
fi

# ---------------------------------------------------------------------------
# 6. Summary
# ---------------------------------------------------------------------------
echo ""
echo "Formula updated successfully!"
echo "  Version:             ${VERSION_NUM}"
echo "  SHA256 darwin-arm64: ${SHA256S[darwin-arm64]}"
echo "  SHA256 darwin-x64:   ${SHA256S[darwin-x64]}"
echo "  SHA256 linux-x64:    ${SHA256S[linux-x64]}"
echo "  SHA256 linux-arm64:  ${SHA256S[linux-arm64]}"
echo ""
echo "Updated formula:"
cat "${FORMULA_PATH}"
